config/routes.rb
Rails.application.routes.draw do

     mount Ckeditor::Engine => '/ckeditor'
      root                'static_pages#home'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :update]

      #api
      namespace :api do
        namespace :v1 do
          namespace :consumer do
             resources :cms_pages, only: [:index,:show]
             resources :gallery_types, only: [:index,:show]
             resources :gallery_images, only: [:index,:show]
          end
          resources :gallery_types 
          resources :gallery_images do
              collection { post :sort }
          end
          resources :cms_pages
          resources :settings
          resources :account_activations, only: [:edit,:create]
          resources :password_resets,     only: [:new, :create, :edit, :update, :show]
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :sessions, only: [:create]
        end
      end
end

app/models/cms_page.rb
class CmsPage < ActiveRecord::Base
      before_save   :downcase_page_name
      validates :page_name,  presence: true,uniqueness: { case_sensitive: false }
      validates :title,  presence: true
      validates :description,  presence: true

      private

            # Converts email to all lower-case.
            def downcase_page_name
              self.page_name = page_name.downcase
            end
end

app/controllers/api/v1/cms_pages_controller.rb
class Api::V1::CmsPagesController < Api::V1::BaseController
      before_filter :authenticate_user!
      before_action :set_cms_page, only: [:show, :edit, :update, :destroy]
      # GET /cms_pages
      # GET /cms_pages.json
      def index
        @cms_pages = CmsPage.all
        render(
          json: ActiveModel::ArraySerializer.new(
            @cms_pages,
            each_serializer: Api::V1::CmsPageSerializer,
            root: 'cms_pages'
          )
        )
      end

      # GET /cms_pages/1
      # GET /cms_pages/1.json
      def show
        render(json: Api::V1::CmsPageSerializer.new(@cms_page).to_json)
      end

      # GET /cms_pages/new
      def new
        @cms_page = CmsPage.new
      end

      # GET /cms_pages/1/edit
      def edit
      end

      # POST /cms_pages
      # POST /cms_pages.json
      def create
        @cms_page = CmsPage.new(cms_page_params)
        return api_error(status: 422, errors: @cms_page.errors) unless @cms_page.valid?
        @cms_page.save!
        render(
          json: Api::V1::CmsPageSerializer.new(@cms_page).to_json,
          status: 201,
          location: api_v1_cms_page_path(@cms_page)
        )
      end

      # PATCH/PUT /cms_pages/1
      # PATCH/PUT /cms_pages/1.json
      def update
        respond_to do |format|
          if @cms_page.update(cms_page_params)
            format.html { redirect_to @cms_page, notice: 'Cms page was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @cms_page.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /cms_pages/1
      # DELETE /cms_pages/1.json
      def destroy
        @cms_page.destroy
        respond_to do |format|
          format.html { redirect_to cms_pages_url }
          format.json { head :no_content }
        end
      end

      private

        def switch_tenant
            if @current_user
                if Apartment::Tenant.current != @current_user.tenant_name
                  Apartment::Tenant.switch!(@current_user.tenant_name)
                elsif @current_user
                  Apartment::Tenant.switch! # Revert to the primary tenant
                end
            end
        end

        # Use callbacks to share common setup or constraints between actions.
        def set_cms_page
          @cms_page = CmsPage.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def cms_page_params
          params.require(:cms_page).permit(:page_name, :title, :description)
        end
end

app/controllers/api/v1/consumer/cms_pages_controller.rb
class Api::V1::Consumer::CmsPagesController < Api::V1::Consumer::FoundationController
      before_filter :authenticate_user!
      before_action :set_cms_page, only: [:show]


      def index
        @cms_pages = CmsPage.all
        render(
          json: ActiveModel::ArraySerializer.new(
            @cms_pages,
            each_serializer: Api::V1::Consumer::CmsPageSerializer,
            root: 'cms_pages'
          )
        )
      end

      def show
        render(json: Api::V1::Consumer::CmsPageSerializer.new(@cms_page).to_json)
      end


      private

            def switch_tenant
                if @current_user
                    if Apartment::Tenant.current != @current_user.tenant_name
                      Apartment::Tenant.switch!(@current_user.tenant_name)
                    elsif @current_user
                      Apartment::Tenant.switch! # Revert to the primary tenant
                    end
                end
            end

            # Use callbacks to share common setup or constraints between actions.
            def set_cms_page
              @cms_page = CmsPage.find(params[:id])
            end
end

app/controllers/cms_pages_controller.rb
class CmsPagesController < ApplicationController
      before_action :set_cms_page, only: [:show, :edit, :update, :destroy]

      # GET /cms_pages
      # GET /cms_pages.json
      def index
        @cms_pages = CmsPage.all

        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @cms_pages }
        end
      end

      # GET /cms_pages/1
      # GET /cms_pages/1.json
      def show
        respond_to do |format|
          format.html # show.html.erb
          format.json { render json: @cms_page }
        end
      end

      # GET /cms_pages/new
      def new
        @cms_page = CmsPage.new
      end

      # GET /cms_pages/1/edit
      def edit
      end

      # POST /cms_pages
      # POST /cms_pages.json
      def create
        @cms_page = CmsPage.new(cms_page_params)

        respond_to do |format|
          if @cms_page.save
            format.html { redirect_to @cms_page, notice: 'Cms page was successfully created.' }
            format.json { render json: @cms_page, status: :created }
          else
            format.html { render action: 'new' }
            format.json { render json: @cms_page.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /cms_pages/1
      # PATCH/PUT /cms_pages/1.json
      def update
        respond_to do |format|
          if @cms_page.update(cms_page_params)
            format.html { redirect_to @cms_page, notice: 'Cms page was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @cms_page.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /cms_pages/1
      # DELETE /cms_pages/1.json
      def destroy
        @cms_page.destroy
        respond_to do |format|
          format.html { redirect_to cms_pages_url }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_cms_page
          @cms_page = CmsPage.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def cms_page_params
          params.require(:cms_page).permit(:page_name, :title, :description)
        end
end

app/helpers/cms_pages_helper.rb
module CmsPagesHelper
end

app/views/cms_pages/_form.html.erb
<%= form_for(@cms_page) do |f| %>
  <% if @cms_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cms_page.errors.count, "error") %> prohibited this cms_page from being saved:</h2>

      <ul>
      <% @cms_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_name %><br>
    <%= f.text_field :page_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cms_pages/edit.html.erb
<h1>Editing Cms Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @cms_page %> |
<%= link_to 'Back', cms_pages_path %>

app/views/cms_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cms Pages</h1>

<table>
  <thead>
    <tr>
      <th>Page name</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cms_pages.each do |cms_page| %>
      <tr>
        <td><%= cms_page.page_name %></td>
        <td><%= cms_page.title %></td>
        <td><%= cms_page.description %></td>
        <td><%= link_to 'Show', cms_page %></td>
        <td><%= link_to 'Edit', edit_cms_page_path(cms_page) %></td>
        <td><%= link_to 'Destroy', cms_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>

<%= link_to 'New Cms page', new_cms_page_path %>

app/views/cms_pages/new.html.erb
<h1>New Cms Page</h1>

<%= render 'form' %>

<%= link_to 'Back', cms_pages_path %>

app/views/cms_pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page name:</strong>
  <%= @cms_page.page_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cms_page.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cms_page.description %>
</p>

<%= link_to 'Edit', edit_cms_page_path(@cms_page) %> |
<%= link_to 'Back', cms_pages_path %>