config/routes.rb
Rails.application.routes.draw do

     mount Ckeditor::Engine => '/ckeditor'
      root                'static_pages#home'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :update]

      #api
      namespace :api do
        namespace :v1 do
          namespace :consumer do
             resources :cms_pages, only: [:index,:show]
             resources :gallery_types, only: [:index,:show]
             resources :gallery_images, only: [:index,:show]
          end
          resources :gallery_types 
          resources :gallery_images do
              collection { post :sort }
          end
          resources :cms_pages
          resources :settings
          resources :account_activations, only: [:edit,:create]
          resources :password_resets,     only: [:new, :create, :edit, :update, :show]
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :sessions, only: [:create]
        end
      end
end

app/controllers/api/v1/consumer/gallery_types_controller.rb
class Api::V1::Consumer::GalleryTypesController < Api::V1::Consumer::FoundationController
      before_filter :authenticate_user!
      before_action :set_gallery_type, only: [:show]

      def index
           if params[:tag_id]
                @tags = Tag.all
           else
                @gallery_types = GalleryType.all
                 render(
                            json: ActiveModel::ArraySerializer.new(
                              @gallery_types,
                              each_serializer: Api::V1::Consumer::GalleryTypeSerializer,
                              root: 'gallery_types'
                      )
                 )
           end
      end

      def show
           render(json: Api::V1::Consumer::GalleryTypeSerializer.new(@gallery_type).to_json)
      end

      private
        # Use callbacks to share common setup or constraints between actions.
       def set_gallery_type
            @gallery_type = GalleryType.includes(:gallery_images).find(params[:id])

      end

        # Never trust parameters from the scary internet, only allow the white list through.
      def gallery_type_params
            params.require(:gallery_type).permit(:name, :height, :width, :is_video, :image_type)
      end
end

app/controllers/api/v1/gallery_types_controller.rb
class Api::V1::GalleryTypesController < Api::V1::BaseController
      before_filter :authenticate_user!
      before_action :set_gallery_type, only: [:show, :edit, :update, :destroy]

      # GET /gallery_types
      # GET /gallery_types.json
      def index
           @gallery_types = GalleryType.all
            render(
                      json: ActiveModel::ArraySerializer.new(
                        @gallery_types,
                        each_serializer: Api::V1::GalleryTypeSerializer,
                        root: 'gallery_types'
                  )
            )
      end

      # GET /gallery_types/1
      # GET /gallery_types/1.json
      def show
           render(json: Api::V1::GalleryTypeSerializer.new(@gallery_type).to_json)
      end

      # GET /gallery_types/new
      def new
            @gallery_type = GalleryType.new
      end

      # GET /gallery_types/1/edit
      def edit
      end

      # POST /gallery_types
      # POST /gallery_types.json
      def create
            @gallery_type = GalleryType.new(gallery_type_params)
            return api_error(status: 422, errors: @gallery_type.errors) unless @gallery_type.valid?
            @gallery_type.save!
            render(
                json: Api::V1::GalleryTypeSerializer.new(@gallery_type).to_json,
                status: 201,
                location: api_v1_gallery_type_path(@gallery_type)
            )
      end

      # PATCH/PUT /gallery_types/1
      # PATCH/PUT /gallery_types/1.json
      def update
            respond_to do |format|
                   if @gallery_type.update(gallery_type_params)
                        format.html { redirect_to @gallery_type, notice: 'Gallery type was successfully updated.' }
                        format.json { head :no_content }
                   else
                        format.html { render action: 'edit' }
                        format.json { render json: @gallery_type.errors, status: :unprocessable_entity }
                   end
            end
      end

      # DELETE /gallery_types/1
      # DELETE /gallery_types/1.json
      def destroy
            @gallery_type.destroy
            respond_to do |format|
                  format.html { redirect_to gallery_types_url }
                  format.json { head :no_content }
            end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
       def set_gallery_type
            @gallery_type = GalleryType.find(params[:id])
      end

        # Never trust parameters from the scary internet, only allow the white list through.
      def gallery_type_params
            params.require(:gallery_type).permit(:name, :height, :width, :is_video, :image_type)
      end
end

app/helpers/gallery_types_helper.rb
module GalleryTypesHelper
end

app/views/gallery_types/_form.html.erb
<%= form_for(@gallery_type) do |f| %>
  <% if @gallery_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_type.errors.count, "error") %> prohibited this gallery_type from being saved:</h2>

      <ul>
      <% @gallery_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.number_field :width %>
  </div>
  <div class="field">
    <%= f.label :is_video %><br>
    <%= f.check_box :is_video %>
  </div>
  <div class="field">
    <%= f.label :image_type %><br>
    <%= f.text_field :image_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_types/edit.html.erb
<h1>Editing Gallery Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_type %> |
<%= link_to 'Back', gallery_types_path %>

app/views/gallery_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gallery Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Width</th>
      <th>Is video</th>
      <th>Image type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_types.each do |gallery_type| %>
      <tr>
        <td><%= gallery_type.name %></td>
        <td><%= gallery_type.height %></td>
        <td><%= gallery_type.width %></td>
        <td><%= gallery_type.is_video %></td>
        <td><%= gallery_type.image_type %></td>
        <td><%= link_to 'Show', gallery_type %></td>
        <td><%= link_to 'Edit', edit_gallery_type_path(gallery_type) %></td>
        <td><%= link_to 'Destroy', gallery_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery type', new_gallery_type_path %>

app/views/gallery_types/new.html.erb
<h1>New Gallery Type</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_types_path %>

app/views/gallery_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gallery_type.name %>
</p>

<p>
  <strong>Height:</strong>
  <%= @gallery_type.height %>
</p>

<p>
  <strong>Width:</strong>
  <%= @gallery_type.width %>
</p>

<p>
  <strong>Is video:</strong>
  <%= @gallery_type.is_video %>
</p>

<p>
  <strong>Image type:</strong>
  <%= @gallery_type.image_type %>
</p>

<%= link_to 'Edit', edit_gallery_type_path(@gallery_type) %> |
<%= link_to 'Back', gallery_types_path %>