config/routes.rb
Rails.application.routes.draw do

     mount Ckeditor::Engine => '/ckeditor'
      root                'static_pages#home'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :update]

      #api
      namespace :api do
        namespace :v1 do
          namespace :consumer do
             resources :cms_pages, only: [:index,:show]
             resources :gallery_types, only: [:index,:show]
             resources :gallery_images, only: [:index,:show]
          end
          resources :gallery_types 
          resources :gallery_images do
              collection { post :sort }
          end
          resources :cms_pages
          resources :settings
          resources :account_activations, only: [:edit,:create]
          resources :password_resets,     only: [:new, :create, :edit, :update, :show]
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :sessions, only: [:create]
        end
      end
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/api/v1/settings_controller.rb
class Api::V1::SettingsController < Api::V1::BaseController
      before_action :set_setting, only: [:show, :edit, :update, :destroy]

      # GET /settings
      # GET /settings.json
      def index
             @settings = Setting.all
             render(
              json: ActiveModel::ArraySerializer.new(
                @settings,
                each_serializer: Api::V1::SettingSerializer,
                root: 'settings'
              )
            )
      end

      # GET /settings/1
      # GET /settings/1.json
      def show
           render(json: Api::V1::SettingSerializer.new(@setting).to_json)
      end

      # GET /settings/new
      def new
        @setting = Setting.new
      end

      # GET /settings/1/edit
      def edit
      end

      # POST /settings
      # POST /settings.json
      def create
            @setting = Setting.new(setting_params)
            return api_error(status: 422, errors: @setting.errors) unless @setting.valid?
            @setting.save!
            render(
                  json: Api::V1::SettingSerializer.new(@setting).to_json,
                  status: 201,
                  location: api_v1_setting_path(@setting.id)
            )
      end

      # PATCH/PUT /settings/1
      # PATCH/PUT /settings/1.json
      def update
        respond_to do |format|
          if @setting.update(setting_params)
            format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @setting.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /settings/1
      # DELETE /settings/1.json
      def destroy
            @setting.destroy
            respond_to do |format|
                format.html { redirect_to settings_url }
                format.json { head :no_content }
            end
      end

      private
             # Use callbacks to share common setup or constraints between actions.
            def set_setting
              @setting = Setting.find(params[:id])
            end

            # Never trust parameters from the scary internet, only allow the white list through.
            def setting_params
              params.require(:setting).permit(:verify_user)
            end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :verify_user %><br>
    <%= f.check_box :verify_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settings</h1>

<table>
  <thead>
    <tr>
      <th>Verify user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.verify_user %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Verify user:</strong>
  <%= @setting.verify_user %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>