config/routes.rb
Rails.application.routes.draw do

     mount Ckeditor::Engine => '/ckeditor'
      root                'static_pages#home'
      resources :account_activations, only: [:edit]
      resources :password_resets,     only: [:new, :create, :edit, :update]

      #api
      namespace :api do
        namespace :v1 do
          namespace :consumer do
             resources :cms_pages, only: [:index,:show]
             resources :gallery_types, only: [:index,:show]
             resources :gallery_images, only: [:index,:show]
          end
          resources :gallery_types 
          resources :gallery_images do
              collection { post :sort }
          end
          resources :cms_pages
          resources :settings
          resources :account_activations, only: [:edit,:create]
          resources :password_resets,     only: [:new, :create, :edit, :update, :show]
          resources :users, only: [:index, :create, :show, :update, :destroy]
          resources :sessions, only: [:create]
        end
      end
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
      #GEMS USED
      #ACCESSORS
      attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :processing, :deferred_image, :tag_list
      attr_writer :deferred_image
      #ASSOCIATIONS
      has_many :taggings
      has_many :tags, through: :taggings
      has_attached_file :avatar, :url  => "/uploads/:id/:style_:basename.:extension",:path => "/home/public/innboxapi.in/public/innbox_api/public/uploads/:id/:style_:basename.:extension", styles: lambda { |a| a.instance.is_image? ? {:large => a.instance.styles,:medium => "300x300!", :thumb => "100x100!"}  : {:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10}, :medium => { :geometry => "300x300#", :format => 'jpg', :time => 10}}},
  processors: lambda { |a| a.is_video? ? "" : [ :cropper ] }
      belongs_to :gallery_type, class_name:"GalleryType"
      #VALIDATIONS
      validates :title, :presence => true
      validates_attachment_content_type :avatar, :content_type => ['application/x-shockwave-flash', 'application/x-shockwave-flash', 'application/flv', 'video/mp4','image/jpeg', 'image/jpg', 'image/png']
      #CALLBACKS
      after_update :reprocess_avatar, :if => :cropping?
      after_create :update_sort_order
      after_save :assign_deferred_image
      before_save :link_validation
      #SCOPES
      #CUSTOM SCOPES
      #OTHER METHODS

      def decode_image_data

          if self.image_data.present?
              # If image_data is present, it means that we were sent an image over
              # JSON and it needs to be decoded.  After decoding, the image is processed
              # normally via Paperclip.
              if self.image_data.present?
                  data = StringIO.new(Base64.decode64(self.image_data))
                  data.class.class_eval {attr_accessor :original_filename, :content_type}
                  data.original_filename = self.id.to_s + ".png"
                  data.content_type = "image/png"

                  self.avatar = data
              end
          end
      end

      def update_sort_order
         @sort_maximum= GalleryImage.maximum("sort_order") ? GalleryImage.maximum("sort_order") : 0
          @sort_maximum+=1
          self.sort_order=@sort_maximum
          self.save
      end

      def validate_image_size
        if avatar.file? && avatar.size > get_current_file_size_limit
          errors.add_to_base(" ... Your error message")
        end
      end 

      def styles
        if self.gallery_type.present?
          return "#{self.gallery_type.width}x#{self.gallery_type.height}!"
        else
          return "1000x1000!"
        end
      end

      def is_image?
        [ 'image/jpeg', 
          'image/jpg',
          'image/png' ].include?(avatar.content_type)
      end

      def is_video?
        [ 'application/x-mp4',
          'video/mp4',
          'video/mpeg',
          'video/quicktime',
          'video/x-la-asf',
          'video/x-ms-asf',
          'video/x-msvideo',
          'video/x-sgi-movie',
          'video/x-flv',
          'flv-application/octet-stream',
          'video/3gpp',
          'video/3gpp2',
          'video/3gpp-tt',
          'video/BMPEG',
          'video/BT656',
          'video/CelB',
          'video/DV',
          'video/H261',
          'video/H263',
          'video/H263-1998',
          'video/H263-2000',
          'video/H264',
          'video/JPEG',
          'video/MJ2',
          'video/MP1S',
          'video/MP2P',
          'video/MP2T',
          'video/mp4',
          'video/MP4V-ES',
          'video/MPV',
          'video/mpeg4',
          'video/mpeg4-generic',
          'video/nv',
          'video/parityfec',
          'video/pointer',
          'video/raw',
          'video/rtx' ].include?(avatar.content_type)
      end

      def cropping?
        !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
      end


      def avatar_geometry(style = :original)
        @geometry ||= {}
        @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
      end

      #JOBS
      #PRIVATE 

      def reprocess_avatar
        return unless (cropping? && !processing)
        self.processing = true
        avatar.reprocess!
        self.processing = false
      end

      def assign_deferred_image
        if @deferred_image
          self.avatar = @deferred_image
          @deferred_image = nil
          save!
        end
      end
      
      def link_validation
        if self.link.match("https://").present?
        elsif self.link.match("http://").present?
        else
          self.link = "http://" + self.link
        end
      end


      def self.tagged_with(name)
          Tag.find_by_name!(name).gallery_images
      end

      def self.tag_counts
          Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
      end
      
      def tag_list
        tags.map(&:name).join(", ")
      end
      
      def tag_list=(names)
        self.tags = names.split(",").map do |n|
          Tag.where(name: n.strip).first_or_create!
        end
      end
end

app/controllers/api/v1/consumer/gallery_images_controller.rb
class Api::V1::Consumer::GalleryImagesController < Api::V1::Consumer::FoundationController
      before_filter :authenticate_user!
      before_action :set_gallery_image, only: [:show]
      before_action :set_gallery_type,only: [:show,:index]

      def index
           if params[:tag_name].present?
               @gallery_images = @tag.gallery_images
           else
                @gallery_images = @gallery_type.gallery_images
           end
           render(
                      json: ActiveModel::ArraySerializer.new(
                        @gallery_images,
                        each_serializer: Api::V1::Consumer::GalleryImageSerializer,
                        root: 'gallery_images'
                      )
                )
      end

      def show
           render(json: Api::V1::Consumer::GalleryImageSerializer.new(@gallery_image).to_json)
      end


      private
          # Use callbacks to share common setup or constraints between actions.
            def set_gallery_type
                 if params[:tag_name].present?
                     @tag = Tag.find_by_name(params[:tag_name])
                 else
                     @gallery_type = GalleryType.find(params[:gallery_type_id])
                 end
            end

          # Use callbacks to share common setup or constraints between actions.
          def set_gallery_image
            @gallery_image = GalleryImage.find(params[:id])
          end

          # Never trust parameters from the scary internet, only allow the white list through.
          def gallery_image_params
            params.require(:gallery_image).permit(:avatar, :gallery_type_id, :alt_text, :sort_order, :link, :description, :title, :crop_x, :crop_y, :crop_w, :crop_h, :tag_list)
          end
end

app/controllers/api/v1/gallery_images_controller.rb
class Api::V1::GalleryImagesController < Api::V1::BaseController
      wrap_parameters :gallery_image, include: [:gallery_type_id, :alt_text, :sort_order, :link, :description, :title, :crop_x, :crop_y, :crop_w, :crop_h, :tag_list]
      before_filter :authenticate_user!
      before_action :set_gallery_image, only: [:show, :edit, :update, :destroy]
      before_action :set_gallery_type,only: [:show, :edit, :update, :index, :create]

      # GET /gallery_images
      # GET /gallery_images.json
      def index
            @gallery_images = @gallery_type.gallery_images
            render(
                  json: ActiveModel::ArraySerializer.new(
                    @gallery_images,
                    each_serializer: Api::V1::GalleryImageSerializer,
                    root: 'gallery_images'
                  )
            )
      end

      # GET /gallery_images/1
      # GET /gallery_images/1.json
      def show
           render(json: Api::V1::GalleryImageSerializer.new(@gallery_image).to_json)
      end

      # GET /gallery_images/new
      def new
        @gallery_image = GalleryImage.new
      end

      # GET /gallery_images/1/edit
      def edit
      end

      # POST /gallery_images
      # POST /gallery_images.json
      def create
            uploaded_io = params[:avatar][:original_filename]
            f = File.open(Rails.root.join('public', 'uploads', uploaded_io.gsub(" ","_")))  
            @gallery_image = GalleryImage.new(gallery_image_params)
            return api_error(status: 422, errors: @gallery_image.errors) unless @gallery_image.valid?
            @gallery_image.avatar = f
            File.delete(Rails.root.join('public', 'uploads', uploaded_io.gsub(" ","_")))   
            @gallery_image.save!
            render(
                  json: Api::V1::GalleryImageSerializer.new(@gallery_image).to_json,
                  status: 201,
                  location: api_v1_gallery_image_path(@gallery_image)
            )
      end

      # PATCH/PUT /gallery_images/1
      # PATCH/PUT /gallery_images/1.json
      def update
        respond_to do |format|
          if @gallery_image.update(gallery_image_params)
             if  params[:avatar].class != String

                  uploaded_io = params[:avatar][:original_filename]
                  f = File.open(Rails.root.join('public', 'uploads', uploaded_io.gsub(" ","_"))) 
                  @gallery_image.avatar = f
                 @gallery_image.save 
              end
             
            format.html { redirect_to @gallery_image, notice: 'Gallery image was successfully updated.' }
            format.json { head :no_content }
          else
            format.html { render action: 'edit' }
            format.json { render json: @gallery_image.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /gallery_images/1
      # DELETE /gallery_images/1.json
      def destroy
        @gallery_image.destroy
        respond_to do |format|
          format.html { redirect_to gallery_images_url }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_gallery_type
          @gallery_type = GalleryType.find(params[:gallery_type_id])
        end

        # Use callbacks to share common setup or constraints between actions.
        def set_gallery_image
          @gallery_image = GalleryImage.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def gallery_image_params
          params.require(:gallery_image).permit(:avatar, :gallery_type_id, :alt_text, :sort_order, :link, :description, :title, :crop_x, :crop_y, :crop_w, :crop_h, :tag_list)
        end
end

app/helpers/gallery_images_helper.rb
module GalleryImagesHelper
end

app/views/gallery_images/_form.html.erb
<%= form_for(@gallery_image) do |f| %>
  <% if @gallery_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery_image.errors.count, "error") %> prohibited this gallery_image from being saved:</h2>

      <ul>
      <% @gallery_image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :gallery_type_id %><br>
    <%= f.number_field :gallery_type_id %>
  </div>
  <div class="field">
    <%= f.label :alt_text %><br>
    <%= f.text_field :alt_text %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br>
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gallery_images/edit.html.erb
<h1>Editing Gallery Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery_image %> |
<%= link_to 'Back', gallery_images_path %>

app/views/gallery_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gallery Images</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Gallery type</th>
      <th>Alt text</th>
      <th>Sort order</th>
      <th>Link</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gallery_images.each do |gallery_image| %>
      <tr>
        <td><%= gallery_image.avatar %></td>
        <td><%= gallery_image.gallery_type_id %></td>
        <td><%= gallery_image.alt_text %></td>
        <td><%= gallery_image.sort_order %></td>
        <td><%= gallery_image.link %></td>
        <td><%= gallery_image.description %></td>
        <td><%= gallery_image.title %></td>
        <td><%= link_to 'Show', gallery_image %></td>
        <td><%= link_to 'Edit', edit_gallery_image_path(gallery_image) %></td>
        <td><%= link_to 'Destroy', gallery_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery image', new_gallery_image_path %>

app/views/gallery_images/new.html.erb
<h1>New Gallery Image</h1>

<%= render 'form' %>

<%= link_to 'Back', gallery_images_path %>

app/views/gallery_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avatar:</strong>
  <%= @gallery_image.avatar %>
</p>

<p>
  <strong>Gallery type:</strong>
  <%= @gallery_image.gallery_type_id %>
</p>

<p>
  <strong>Alt text:</strong>
  <%= @gallery_image.alt_text %>
</p>

<p>
  <strong>Sort order:</strong>
  <%= @gallery_image.sort_order %>
</p>

<p>
  <strong>Link:</strong>
  <%= @gallery_image.link %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gallery_image.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @gallery_image.title %>
</p>

<%= link_to 'Edit', edit_gallery_image_path(@gallery_image) %> |
<%= link_to 'Back', gallery_images_path %>